
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages.Commons.Dialogs;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class EditPlainTextViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new EditPlainTextViewModel();
        }
    }
}
