
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages.Gallery;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class NewDocumentViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new NewDocumentViewModel();
        }
    }
}
