
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages.Templates;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class NewElementViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new NewElementViewModel();
        }
    }
}
