
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class BookmarkViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new BookmarkViewModel();
        }
    }
}
