
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages.Documents.Share;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class CharacterPergamynStyleViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new CharacterPergamynStyleViewModel();
        }
    }
}
