
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages.Interactions;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class CharacterContractViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new CharacterContractViewModel();
        }
    }
}
