
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages.Documents;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class CharacterRelPartViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
        }
    }
}
