
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.ViewModels;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class TabBaseAppViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
        }
    }
}
