// <auto-generated>

namespace Acorisoft.FutureGL.MigaTest
{
    public class Test
    {
        public void Initialize()
        {
            Tester.Initialize(@"c:\config.ini");
        }
        
        public void TestMethods()
        {
            // Dialogs
            
            // ViewModels
            
            // Controls
            
            // Models
            Tester.Test<Test>();
            Tester.Test<Test>();
            Tester.Test<Test>();
            Tester.Test<Test>();
        }
    }
}