
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.ViewModels;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class AppViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new AppViewModel();
        }
    }
}
