
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages.Universe;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class BrowsablePropertyViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new BrowsablePropertyViewModel();
        }
    }
}
