
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages.Dialogs;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class BugReportViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new BugReportViewModel();
        }
    }
}
