
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages.Composes;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class ComposeEditorViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new ComposeEditorViewModel();
        }
    }
}
