
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages.Universe;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class DeclarationConceptViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new DeclarationConceptViewModel();
        }
    }
}
