
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class DirectoryManagerViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new DirectoryManagerViewModel();
        }
    }
}
