
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.ViewModels;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class IsolatedViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new IsolatedViewModel();
        }
    }
}
