
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.ViewModels;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class MasterDetailViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new MasterDetailViewModel<,>();
        }
    }
}
