
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages.Templates;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class ModuleManifestViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new ModuleManifestViewModel();
        }
    }
}
