
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages.Services;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class MusicViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new MusicViewModel();
        }
    }
}
