
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages.Relatives;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class NewRelativePresetViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new NewRelativePresetViewModel();
        }
    }
}
