
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages.Documents;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class OtherDocumentViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new OtherDocumentViewModel();
        }
    }
}
