
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages.Startup;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class StartupWorldViewViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new StartupWorldViewViewModel();
        }
    }
}
