
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class StoryboardSegmentsViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new StoryboardSegmentsViewModel();
        }
    }
}
