
// <auto-generated/>

using Acorisoft.FutureGL.MigaStudio.Pages.Commons;

namespace Acorisoft.FutureGL.MigaStudio
{
    [TestClass, TestCategory("ViewModel")]
    public class StickyNotePartViewModelFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new StickyNotePartViewModel();
        }
    }
}
